name: "Deploy codigofacilito!"

on:
  push:
    branches:
      - main

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Starting deployment process for codigofacilito..."
      - run: echo "Deploying codigofacilito!"
      - run: echo "Deployment completed successfully!"
      - run: echo "You can now access codigofacilito at https://codigofacilito.com"
      - run: echo "Thank you for using codigofacilito!"
