name: Deploy to server!
on: push

jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo!
        uses: actions/checkout@v2
      - run: echo "Hola mundo desde la rama main!"
